config/routes.rb
Rails.application.routes.draw do

  root "welcome#home"

#users and users problem paths
  resources :users do
    resources :problems, except: [:index]
    post '/problems/:id/comments', to: 'problem_comments#create', as: :comment_problem
    get '/problems/:id/comments', to: 'problem_comments#index'
    delete '/problems/:id', to: 'problems#delete', as: :delete_problem
  end

  get '/active_problems', to: 'problems#index'
  post '/help_problem/:id', to: 'helped_problems#help_problem', as: :help_problem
  get '/users/:user_id/problems', to: 'problems#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/facebook/callback' => 'sessions#create'
 
  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :user
  has_many :problem_categories
  has_many :categories, through: :problem_categories
  has_many :helped_problems
  has_many :helped, through: :helped_problems, source: 'user'
  has_many :problem_comments
  validates :name, :description, presence: true
  accepts_nested_attributes_for :categories
  scope :active_problems, -> {where(active: true)}

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute[:name].present?
        category = Category.find_or_create_by(category_attribute)
        if !self.categories.include?(category)
          self.categories << category
        end
      end
    end
  end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_user_and_problem, only:[:show, :edit, :update, :destroy]
  before_action :allowed_user, only:[:edit, :destroy]

  def index
    @problems = Problem.active_problems
    respond_to do |format|
      format.html{render :index}
      format.json{render json: @problems, status: 200}
    end
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @problem = @user.problems.new(user_id: params[:user_id])
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @problem = Problem.new(problem_params)
    if @problem.save
      redirect_to user_problem_path(@problem.user_id, @problem)
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html{render :show}
      format.json{render json: @problem, status: 200}
    end
  end

  def edit
  end

  def update
    @problem.update(problem_params)
    redirect_to user_problem_path(@user, @problem), flash: {notice: "Your problem has been updated!"}
  end

  def destroy
    @problem.destroy
    redirect_to root_path, flash:{notice: "Your problem has been deleted"}
  end

  def redirect
    redirect_to new_user_problem_path(params[:user_id])
  end

  private

  def problem_params
    params.require(:problem).permit(:name, :description, :user_id, :active, :school, category_ids:[], categories_attributes:[:name])
  end

  def set_user_and_problem
    if params[:user_id] && User.exists?(params[:user_id])
      @user = User.find_by(id: params[:user_id])
      @problem = @user.problems.find_by(id: params[:id])
      if @problem.nil?
        redirect_to active_problems_path, flash:{alert: "That problem does not exist."}
      end
    else
      redirect_to active_problems_path, flash:{alert: "That user does not exist."}
    end
  end

  def allowed_user
    @problem = Problem.find_by(id: params[:id])
    unless current_user == @problem.user
      redirect_to active_problems_path, flash:{alert: "You don't have access to that."}
    end
  end



end

app/helpers/problems_helper.rb
module ProblemsHelper

  def schools
    [
      ['Bryson Elementary'],
      ['Chisholm Ridge Elementary'],
      ['Comanche Springs Elementary'],
      ['Copper Creek Elementary'],
      ['Dozier Elementary'],
      ['Eagle Mountain Elementary'],
      ['Elkins Elementary'],
      ['Gililland Elementary'],
      ['Greenfield Elementary'],
      ['High Country Elementary'],
      ['Lake Pointe Elementary'],
      ['Northbrook Elementary'],
      ['Parkview Elementary'],
      ['Remington Point Elementary'],
      ['Saginaw Elementary'],
      ['Willow Creek Elementary'],
      ['Creekview Middle School'],
      ['Ed Willkie Middle School'],
      ['Highland Middle School'],
      ['Marine Creek Middle School'],
      ['Prairie Vista Middle School'],
      ['Wayside Middle School'],
      ['Boswell High School'],
      ['Chisholm Trail High School'],
      ['Saginaw High School'],
      ['Watson High School'],

    ]
end


  def edit_problem(user, problem)
    link_to "Edit Problem", edit_user_problem_path(user, problem), id: 'edit-problem'
  end

  def delete_problem(user, problem)
    link_to "Delete Problem", user_delete_problem_path(user, problem), id: 'delete-problem', method: :delete, confirm: "Are you sure?"
  end

end

app/views/problems/_form.html.erb
<%= form_for [@user, @problem] do |f| %>
<% if @problem.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h4>

    <ul>
    <% @problem.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.hidden_field :user_id %>

<!--The beginning of the form field -->
  <div class="jumbotron">
      <div>
        <%= f.label :problem_name %>
        <%= f.text_field :name, placeholder: "problem name" %>
      </div>

      <div>
        <%= f.label :Student_Name %>
        <%= f.text_field :city %>
      </div>

      <div>
        <%= f.label :School %>
        <%= f.select(:school, options_for_select(schools)) %>
      </div>

      <div>
        <%= f.label :active, "Activate the Math Problem" %>
        <%= f.check_box :active %>
      </div>

      <p>Choose some Categories!</p>

      <div>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name%>
      </div>

      <div>
      <%= f.fields_for :categories, @problem.categories.build do |categories_fields| %>
        <%= categories_fields.label :name, "Create a new category" %>
        <%= categories_fields.text_field :name %>
      <% end %>
      </div>

      <div class="label">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description,  class: "form-group" %>
      </div>

      <div class="actionButtons">
        <%= f.submit %>
      </div>
  </div>

<% end %>

app/views/problems/edit.html.erb
<h1> Edit <%= @problem.name %> </h1>

<%= render 'form' %>

app/views/problems/index.html.erb
<h1>All Math Problems!</h1>

<table class="table table-hover">
  <tr>
    <th>Problem Name</th>
    <th>Problem Creator</th>
  </tr>
  <% @problems.each do |problem| %>
    <tr>
      <th><%= link_to problem.name, user_problem_path(problem.user_id, problem) %></th>
      <th><%= link_to problem.user.username, user_path(problem.user) %> </th>
    </tr>
  <% end %>
</table>

app/views/problems/new.html.erb
<h1> Create a New Math Problem! </h1>

<%= render 'form' %>

app/views/problems/show.html.erb
<div class="title" id="problem_title">
  <h1><%=@problem.name%></h1>
</div>

<div>
  <center><%=button_to "Help this Student",help_problem_path(@problem.id) if guest_user(@user)%></center>
</div>

<div>
  <center>
    <%if correct_user(@user) %>
      <%= edit_problem(@user, @problem)%> - <%= delete_problem(@user, @problem) %>
    <% end %>
  </center>
</div>

      <h4 class="text-danger">Problem Name:</h4><%=@problem.name%>
        </br>
        </br>
      <h4 class="text-danger">Student's Name:</h4> <%=@problem.user.username%>
        </br>
        </br>
      <h4 class="text-danger">Student's School:</h4><%=@problem.school%>
        <br>
        </br>

<div class="problem-description">
  <h3>Description:</h3>
  <p class="text-info"><%=@problem.description%></p>
</div>
<br>

<div class="categories">
  <h4>Relevant Categories:</h4>
    <ul class="category-list">
        <% @problem.categories.each do |category| %>
          <li class="category-item"> <%=link_to category.name, category_path(category)%> </li>
        <% end %>
    </ul>
</div>

<br>

<div>
  <%if helped_user(current_user, @problem) %>
    <p> Contact this user to collaborate: <%=@user.email%></p>
  <% end %>
</div>

<div class="js-next" data-uid="<%=@user.id%>" data-id="<%=@problem.id%>">
<br>
  <button class="btn btn-primary">Next Problem</button>
</div>
<br>
<div class="form-group">
  <%=form_for(ProblemComment.new, url: user_comment_problem_path(@user, @problem)) do |f|%>
    <%=f.hidden_field :user_id, value: current_user.id if current_user%>
    <%=f.hidden_field :problem_id, value: @problem.id, id: 'hidden-problemId' %>
    <%= f.text_area :comment, class: "form-control"%> <br>
    <%= f.submit "Submit Comment", id: 'comment-button' %>
  <% end %>
</div>

<a href=# class="show-comments">Show Comments</a>
<div class="comments">
  <ol class="comment-list">
  </ol>
</div>