config/routes.rb
Rails.application.routes.draw do

  root "welcome#home"

#users and users problem paths
  resources :users do
    resources :problems, except: [:index]
    post '/problems/:id/comments', to: 'problem_comments#create', as: :comment_problem
    get '/problems/:id/comments', to: 'problem_comments#index'
    delete '/problems/:id', to: 'problems#delete', as: :delete_problem
  end

  get '/active_problems', to: 'problems#index'
  post '/help_problem/:id', to: 'helped_problems#help_problem', as: :help_problem
  get '/users/:user_id/problems', to: 'problems#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/facebook/callback' => 'sessions#create'
 
  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :problems
  has_many :helped_problems
  has_many :problems_helped, through: :helped_problems, source: 'problem'
  has_many :problem_comments
  validates :username, presence: true
  validates :email, presence: true

  def add_problem(problem)
    if self.problems_helped.where(id: problem.id).empty?
      HelpedProblem.create(user: self, problem: problem)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  before_action :access_user, only:[:edit, :update]

  def new
    if logged_in?
      redirect_to user_path(current_user), flash:{notice: "You are already logged in!"}
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:password] == params[:password_confirmation] && @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @user, status: 200}
    end 
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user, flash:{notice: "Your account has been successfully updated!"}
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to active_problems_path, flash:{alert: "The user does not exist."}
  end

  def access_user
    @user = User.find_by(id: params[:id])
    unless current_user == @user
      redirect_to active_problems_path, flash:{alert: "Hey you don't have access to that."}
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def correct_user(user)
    user == current_user
  end

  def guest_user(user)
    user != current_user
  end

  def helped_user(user, problem)
    user.problems_helped.include?(problem) if user 
  end

end

app/views/users/_begin_form.html.erb
<!--
<%= form_for user do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%=f.label :username%>
    <%=f.text_field :username%>
  <div>-->

app/views/users/_edit_form.html.erb
<%= form_for user do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%=f.label :username%>
    <%=f.text_field :username%>
  <div>
<!-- everything above this line create partial-->

  <div>
    <%=f.label :email%>
    <%=f.text_field :email%>
  <div>

  <div>
    <%=f.label :phone_number, "Phone Number (Optional)"%>
    <%=f.text_field :phone_number%>
  <div>

  <div class="action">
    <%=f.submit "Submit"%>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%=f.label :username%>
    <%=f.text_field :username%>
  <div>
<!-- everything above this line create partial-->
  
  
  <div>
    <%=f.label :password%>
    <%=f.password_field :password%>
  <div>

  <div>
    <%=f.label :password_confirmation, "Password Confirmation"%>
    <%=f.password_field :password_confirmation%>
  </div>

  <div>
    <%=f.label :email%>
    <%=f.text_field :email%>
  <div>

  <div>
    <%=f.label :phone_number, "Phone Number (Optional)"%>
    <%=f.text_field :phone_number%>
  <div>

  <div class="action">
    <%=f.submit "Submit"%>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit this User </h1>

<%=render partial: 'edit_form', locals: {user: @user}%>
<!--adding this local, elimates the need to use the @user instance variable in the associated edit form-->

app/views/users/new.html.erb
 <h2> Welcome to the family, please sign up here! </h2>

 <%=render partial: 'form', locals: {user: @user}%>

<%= link_to "Back", root_path %>

app/views/users/show.html.erb
<h3><%= link_to "edit user", edit_user_path %></h3>
</br>

<h2> <%= @user.username %>'s Maths Problems</h2>

<% if @user.problems.empty? %>
  You currently have no problems, please click <%= link_to "here", new_user_problem_path(@user)%> to add one!
<% else %>
  <table class="table table-hover">
    <tr class="table-active">
      <th>Math Problem Name</th>
      <th>Active?</th>
      <th>More</th>
    </tr>
<% @user.problems.each do |problem| %>
    <tr>
      <td><%= link_to problem.name, user_problem_path(@user, problem) %></td></button></td>

      <td><%= problem.active%></td>

<td><%= link_to "Details...", user_problem_path(@user, problem), class: "btn btn-info" %></td>
      <!---->
<!--<td><button class="js-more" data-uid="<%=@user.id%>" data-id="<%= problem.id %>">Details..</button></td>-->

    </tr>
    <% end %>
  </table>

<% end %>
<div id='problem-display'>
</div>

<% if correct_user(@user) %>
  <p><%= link_to "Add new problem", new_user_problem_path(@user)%></p>
  <br>
  <b> Your are helping with these problems: </b>
  <ul>
    <%@user.problems_helped.each do |problem|%>
      <li><%=link_to problem.name, user_problem_path(problem.user, problem)%></li>
    <% end %>
  </ul>
<% end %>