config/routes.rb
Rails.application.routes.draw do

  root "welcome#home"

#users and users problem paths
  resources :users do
    resources :problems, except: [:index]
    post '/problems/:id/comments', to: 'problem_comments#create', as: :comment_problem
    get '/problems/:id/comments', to: 'problem_comments#index'
    delete '/problems/:id', to: 'problems#delete', as: :delete_problem
  end

  get '/active_problems', to: 'problems#index'
  post '/help_problem/:id', to: 'helped_problems#help_problem', as: :help_problem
  get '/users/:user_id/problems', to: 'problems#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/facebook/callback' => 'sessions#create'
 
  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :problem_categories
  has_many :problems, through: :problem_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end


end

app/views/categories/index.html.erb
<h1> All Categories </h1>

<ul class="category-list">
<% @categories.each do |category| %>
  <li class="category-item"><%=link_to category.name, category_path(category)%></li>
<% end %>
</ul>
<a href=# class="more-categories">Load More</a>

app/views/categories/show.html.erb
<h1>All problems under <%=@category.name%></h1>

<ul>
<%@category.problems.each do |problem|%>
  <li><%=link_to problem.name, user_problem_path(problem.user, problem)%></li>
<% end %>
</ul>

<%= link_to "Categories Index", categories_path %>