config/routes.rb
Rails.application.routes.draw do

  root "welcome#home"

#users and users problem paths
  resources :users do
    resources :problems, except: [:index]
    post '/problems/:id/comments', to: 'problem_comments#create', as: :comment_problem
    get '/problems/:id/comments', to: 'problem_comments#index'
    delete '/problems/:id', to: 'problems#delete', as: :delete_problem
  end

  get '/active_problems', to: 'problems#index'
  post '/help_problem/:id', to: 'helped_problems#help_problem', as: :help_problem
  get '/users/:user_id/problems', to: 'problems#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/facebook/callback' => 'sessions#create'
 
  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">

<%if logged_in?%>

  <a class="navbar-brand"><p style="color:red;font-size:12px;">Current User:  <%=current_user.username %></p></a>
 
  
 
  <div class="collapse navbar-collapse" id="navbarColor01">
  </br>
    <ul class="navbar-nav mr-auto">
  </br>
      <li class="nav-item active">
        <a class="nav-link" href="<%= user_path(current_user) %>"/>Home</a>
    </li>

<li class="nav-item active">
    <a class="nav-link" href="/logout" data-method="delete"/>Signout</a>
</li>
  <% elsif !logged_in?%>

<li class="nav-item active">
    <a class="nav-link" href="<%= login_path %>"/>Login</a>
</li>

<li class="nav-item active">
    <a class="nav-link" href="<%= new_user_path %>"/>Sign up</a>
</li>

  <% end %>

<li class="nav-item active">
  <a class="nav-link" href="<%= active_problems_path %>"/>Math Help Needed</a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="<%= categories_path %>"/>Math Categories</a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="<%= root_path %>"/>About</a>
</li>

   </ul>
  </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArithMaTutor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'grid', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--<link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap" rel="stylesheet">-->
  </head>

  <body>

    <%= render 'layouts/navbar' %>
   
<center><%= link_to image_tag("arithmatutor_logo.png") %></center>

    <div class="jumbotron">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      
      <%= yield %>

    </div>

  </body>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
     
      <br>
    <footer class="branding">
      <small>&copy; 2020 <strong>ArithMaTutor</small>
      
    </footer>
 
 
</html>